name: CI
on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-10.15]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        id: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libcurl4-openssl-dev libz-dev libgtk-3-dev

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install curl zlib

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-

      - name: cargo check
        run: cargo check --verbose --workspace --all-targets

      - name: cargo build
        run: cargo build --verbose

      - name: cargo test
        run: cargo test --verbose --workspace

      - name: cargo fmt
        run: cargo fmt --verbose --all -- --check

      - name: cargo clippy
        run: cargo clippy --verbose --workspace
